### ISSUE TITLE
Failing to run bundled executable

### ISSUE THREAD

**Issue by hartmannr76** [wagoodman/bashful#41]
Firstly, this project seems amazing. I'd love to see where it goes.

I just tried running the bundle command using the sample provide on the `README`:
```go
tasks:
    - cmd: echo "Hello, World!"
```
When I just run `bashful run ./sample.yaml`, this runs fine

I get the following output:
`Bundling ./sample.yaml to ./sample.yaml.bundle`

However when I run `./runner`, I'm getting:
`./runner: line 9: ./bashful: No such file or directory`

I tried this with both install variants, `go get` and trying to pull it through `homebrew` with the same results.

**OS**
Mac Sierra (10.12.6)
**Go Version**
```
$ go version  
go version go1.9.2 darwin/amd64
```

Let me know if you need any other info

**Comment by hartmannr76** [comment]
New find: I tried bundling with the full command path: `/usr/local/bin/bashful bundle sample.yaml ` and using this runner executable worked fine. Looks like its [because of this](https://github.com/wagoodman/bashful/blob/e4f4af0a932ca8d5a28d56fafa8e94803e46cd63/main.go#L155). Maybe I'll start poking around through this

**Comment by wagoodman** [comment]
So the problem is that a copy of bashful is included in the bundle... so the fact that it's running `./bashful ...` isn't the problem, but instead I'd bet that it's not properly including a copy of bashful. The self extracting shell script I made doesn't make itself that easy to debug, but I suspect it has to do with not being able to find the path to itself and 'opening' the bundle to see if it's there is the way forward... I should probably add that next :)
