### ISSUE TITLE
Negative ETA being displayed

### ISSUE THREAD

**Issue by muesli** [wagoodman/bashful#48]
Instead of a negative time value an unknown, not-available or infinite symbol might be nicer looking.

**Comment by wagoodman** [comment]
An infinite symbol would look cool, but wouldn't indicate that the ETA is unknown (it indicates that this task will take forever). A simple replacement with `[??:??:??]` or `[unknown]` makes more sense to me. I left the bug initially there since it seemed like a 'negative eta', which I thought would translate to "I was expecting this task to be done X minutes ago"... but the more I look at it the more is just looks like a bug :/.

**Comment by wagoodman** [comment]
I'll go with `[Unknown!]` for commands that have not been seen before (currently shows `[?]`) and `[Overdue!]` for tasks that are past their ETA.
